make -f Makefile2 sfc18lfa.lib T=OSF F=c18 M=OSL G=OSF C=OSA V=OSNONE CLC=0
make -f Makefile2 sfc18lfd.lib T=OSF F=c18 M=OSL G=OSF C=OSD V=OSNONE CLC=0
make -f Makefile2 sfc18lfe.lib T=OSF F=c18 M=OSL G=OSF C=OSE V=OSNONE CLC=0
make -f Makefile2 sfc18lfm.lib T=OSF F=c18 M=OSL G=OSF C=OSM V=OSNONE CLC=0
make -f Makefile2 sfc18lft.lib T=OSF F=c18 M=OSL G=OSF C=OST V=OSNONE CLC=0
make -f Makefile2 sfc18lna.lib T=OSF F=c18 M=OSL G=OSN C=OSA V=OSNONE CLC=0
make -f Makefile2 sfc18lnd.lib T=OSF F=c18 M=OSL G=OSN C=OSD V=OSNONE CLC=0
make -f Makefile2 sfc18lne.lib T=OSF F=c18 M=OSL G=OSN C=OSE V=OSNONE CLC=0
make -f Makefile2 sfc18lnm.lib T=OSF F=c18 M=OSL G=OSN C=OSM V=OSNONE CLC=0
make -f Makefile2 sfc18lnt.lib T=OSF F=c18 M=OSL G=OSN C=OST V=OSNONE CLC=0
make -f Makefile2 sfc18sfa.lib T=OSF F=c18 M=OSS G=OSF C=OSA V=OSNONE CLC=0
make -f Makefile2 sfc18sfd.lib T=OSF F=c18 M=OSS G=OSF C=OSD V=OSNONE CLC=0
make -f Makefile2 sfc18sfe.lib T=OSF F=c18 M=OSS G=OSF C=OSE V=OSNONE CLC=0
make -f Makefile2 sfc18sfm.lib T=OSF F=c18 M=OSS G=OSF C=OSM V=OSNONE CLC=0
make -f Makefile2 sfc18sft.lib T=OSF F=c18 M=OSS G=OSF C=OST V=OSNONE CLC=0
make -f Makefile2 sfc18sna.lib T=OSF F=c18 M=OSS G=OSN C=OSA V=OSNONE CLC=0
make -f Makefile2 sfc18snd.lib T=OSF F=c18 M=OSS G=OSN C=OSD V=OSNONE CLC=0
make -f Makefile2 sfc18sne.lib T=OSF F=c18 M=OSS G=OSN C=OSE V=OSNONE CLC=0
make -f Makefile2 sfc18snm.lib T=OSF F=c18 M=OSS G=OSN C=OSM V=OSNONE CLC=0
make -f Makefile2 sfc18snt.lib T=OSF F=c18 M=OSS G=OSN C=OST V=OSNONE CLC=0

make -f Makefile2 slc18lfa.lib T=OSL F=c18 M=OSL G=OSF C=OSA V=OSNONE CLC=0
make -f Makefile2 slc18lfd.lib T=OSL F=c18 M=OSL G=OSF C=OSD V=OSNONE CLC=0
make -f Makefile2 slc18lfe.lib T=OSL F=c18 M=OSL G=OSF C=OSE V=OSNONE CLC=0
make -f Makefile2 slc18lfm.lib T=OSL F=c18 M=OSL G=OSF C=OSM V=OSNONE CLC=0
make -f Makefile2 slc18lft.lib T=OSL F=c18 M=OSL G=OSF C=OST V=OSNONE CLC=0
make -f Makefile2 slc18lna.lib T=OSL F=c18 M=OSL G=OSN C=OSA V=OSNONE CLC=0
make -f Makefile2 slc18lnd.lib T=OSL F=c18 M=OSL G=OSN C=OSD V=OSNONE CLC=0
make -f Makefile2 slc18lne.lib T=OSL F=c18 M=OSL G=OSN C=OSE V=OSNONE CLC=0
make -f Makefile2 slc18lnm.lib T=OSL F=c18 M=OSL G=OSN C=OSM V=OSNONE CLC=0
make -f Makefile2 slc18lnt.lib T=OSL F=c18 M=OSL G=OSN C=OST V=OSNONE CLC=0
make -f Makefile2 slc18sfa.lib T=OSL F=c18 M=OSS G=OSF C=OSA V=OSNONE CLC=0
make -f Makefile2 slc18sfd.lib T=OSL F=c18 M=OSS G=OSF C=OSD V=OSNONE CLC=0
make -f Makefile2 slc18sfe.lib T=OSL F=c18 M=OSS G=OSF C=OSE V=OSNONE CLC=0
make -f Makefile2 slc18sfm.lib T=OSL F=c18 M=OSS G=OSF C=OSM V=OSNONE CLC=0
make -f Makefile2 slc18sft.lib T=OSL F=c18 M=OSS G=OSF C=OST V=OSNONE CLC=0
make -f Makefile2 slc18sna.lib T=OSL F=c18 M=OSS G=OSN C=OSA V=OSNONE CLC=0
make -f Makefile2 slc18snd.lib T=OSL F=c18 M=OSS G=OSN C=OSD V=OSNONE CLC=0
make -f Makefile2 slc18sne.lib T=OSL F=c18 M=OSS G=OSN C=OSE V=OSNONE CLC=0
make -f Makefile2 slc18snm.lib T=OSL F=c18 M=OSS G=OSN C=OSM V=OSNONE CLC=0
make -f Makefile2 slc18snt.lib T=OSL F=c18 M=OSS G=OSN C=OST V=OSNONE CLC=0

